sudo: required
dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install root-system; fi

  # Dumping stuff for check
  - root-config --version
  - cmake --version

  # Install  NPTool and NPData (needed to run examples suite)
  - cd 
  - git clone https://github.com/adrien-matta/nptool
  - source ~/nptool/nptool.sh
  - cd $NPTOOL/NPLib 
  - cmake -GNinja ./ 
  - ninja install 
  - ./scripts/RootLogon.sh 

install:

script:
  - cd
  - git clone https://github.com/adrien-matta/midas2nptool
  - cd ~/midas2nptool 
  - cmake -GNinja ./
  - make install 

after_success:

branches:
  only:
    - master

addons:
  apt:
    packages:
    - ninja-build

#notifications:
#  email:
#    recipients:
#      - mhd.moukaddam@gmail.com
#    on_success: change
#    on_failure: always
