sudo: required
dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install root-system; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd && wget https://dl.dropboxusercontent.com/u/32340790/travis/nptool_root6_geant10.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf nptool_root6_geant10.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source ~/nptool/nptool.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd ~/nptool/NPLib/scripts; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./RootLogon.sh && cd; fi

  # Dumping stuff for check
  - root-config --version

  #- cd 
  #- git clone https://github.com/moukaddam/midas2nptool

install:

script:
  - cmake --version
  - cd ~/midas2nptool 
  - cmake ./
  - make install 

after_success:

branches:
  only:
    - master

#notifications:
  email:
    recipients:
      - mhd.moukaddam@gmail.com
    on_success: change
    on_failure: always
