sudo: required
dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd && wget https://dl.dropboxusercontent.com/u/32340790/travis/nptool_root6_geant10.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf nptool_root6_geant10.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source ~/nptool_root6_geant10/nptool.sh; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ~/nptool_root6_geant10/NPLib/scripts/RootLogon.sh; fi

  # Dumping stuff for check
  - root-config --version

install:

script:
  - cmake --version
  - cd midas2nptool 
  - cmake ./
  - make install 

after_success:

branches:
  only:
    - midas2nptool

#notifications:
#  email:
#    recipients:
#      - mhd.moukaddam@gmail.com
#    on_success: change
#    on_failure: always
