sudo: required
dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd && wget https://root.cern.ch/download/root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf root_v5.34.36.Linux-ubuntu14-x86_64-gcc4.8.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source ~/root/bin/thisroot.sh; fi

  # Dumping stuff for check
  - root-config --version
  - cmake --version

  # Install  NPTool and NPData (needed to run examples suite)
  - cd 
  - git clone https://github.com/adrien-matta/nptool
  - source ~/nptool/nptool.sh
  - cd $NPTOOL/NPLib 
  - cmake -GNinja ./ -DETLIST="Tiara GeTAMU FPDTamu" 
  - ninja install 
  - ./scripts/RootLogon.sh 

install:

script:
  - cd
  - git clone https://github.com/adrien-matta/midas2nptool
  - cd ~/midas2nptool 
  - source midas2nptool.sh
  - cmake -GNinja ./
  - ninja install 
  - m2n_folder t40_lowgain.txt sample/ .sampleOP/ T40Tree

after_success:

branches:
  only:
    - master

addons:
  apt:
    packages:
    - ninja-build
    - libafterimage0

#notifications:
#  email:
#    recipients:
#      - mhd.moukaddam@gmail.com
#    on_success: change
#    on_failure: always
